name: CI - G1000 Release
on:
  push:
    tags: 
      - g1000-v*
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Package
        run: powershell.exe -noexit .\build.ps1 -Project workingtitle-project-g1000.xml
      - name: Get clean tag name
        uses: olegtarasov/get-tag@v2
        id: tag_name        
      - name: Zip Release Files
        run: Compress-Archive -Path build\* -DestinationPath workingtitle-g1000.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: G1000 ${{ steps.tag_name.outputs.tag }}
          body: This is a test release.
          draft: true
          prerelease: true
      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: workingtitle-g1000.zip
          asset_name: workingtitle-${{ steps.tag_name.outputs.tag }}.zip
          asset_content_type: application/zip
        
